version: 2
updates:
  - package-ecosystem: cargo
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
