/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/channels/{ch_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_messages"];
        put?: never;
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{ch_id}/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{ch_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{msg_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_message"];
        options?: never;
        head?: never;
        patch: operations["update_message"];
        trace?: never;
    };
    "/messages/{msg_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The author sees their own prior versions; a workspace admin sees anyone's,
         *     and that read is audited. Everyone else gets the "edited" marker and nothing
         *     behind it — showing every earlier draft to every reader is a different
         *     product from the one people think they are using.
         */
        get: operations["message_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{msg_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pin_message"];
        delete: operations["unpin_message"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{msg_id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_reactions"];
        put?: never;
        post: operations["add_reaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{msg_id}/reactions/{emoji}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_reaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{msg_id}/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_thread"];
        put?: never;
        post: operations["reply_to_thread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddReactionRequest: {
            emoji: string;
        };
        BotIdentity: {
            /** Format: uuid */
            hook_id: string;
            icon_url?: string | null;
            name: string;
        };
        ConversationMessage: {
            /** Format: uuid */
            client_message_id?: string | null;
            content: string;
            /** Format: uuid */
            conversation_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            edited_at?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            reply_count: number;
            /** Format: uuid */
            thread_parent_id?: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            user_id: string;
        };
        DataList_Message: {
            data: {
                /** Format: uuid */
                channel_id: string;
                /** Format: uuid */
                client_message_id?: string | null;
                content: string;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                deleted_at?: string | null;
                /** Format: uuid */
                id: string;
                is_pinned: boolean;
                metadata: components["schemas"]["MessageMetadata"];
                /** Format: int32 */
                reply_count: number;
                /** Format: uuid */
                thread_parent_id?: string | null;
                /** Format: date-time */
                updated_at: string;
                /** Format: uuid */
                user_id: string;
            }[];
        };
        DataList_MessageEdit: {
            data: {
                /** Format: date-time */
                edited_at: string;
                /** Format: uuid */
                edited_by: string;
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                message_id: string;
                previous_content: string;
            }[];
        };
        DataList_MessageWithReactions: {
            data: (components["schemas"]["Message"] & {
                reactions: components["schemas"]["Reaction"][];
            })[];
        };
        DataList_Reaction: {
            data: {
                /** Format: date-time */
                created_at: string;
                emoji: string;
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                message_id: string;
                /** Format: uuid */
                user_id: string;
            }[];
        };
        MarkReadRequest: {
            /** Format: uuid */
            message_id: string;
        };
        Message: {
            /** Format: uuid */
            channel_id: string;
            /** Format: uuid */
            client_message_id?: string | null;
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: uuid */
            id: string;
            is_pinned: boolean;
            metadata: components["schemas"]["MessageMetadata"];
            /** Format: int32 */
            reply_count: number;
            /** Format: uuid */
            thread_parent_id?: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            user_id: string;
        };
        MessageEdit: {
            /** Format: date-time */
            edited_at: string;
            /** Format: uuid */
            edited_by: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            message_id: string;
            previous_content: string;
        };
        MessageMetadata: {
            bot?: null | components["schemas"]["BotIdentity"];
            /** Format: uuid */
            huddle_id?: string | null;
            /** Format: uuid */
            initiator_id?: string | null;
            kind?: string | null;
        };
        MessageWithReactions: components["schemas"]["Message"] & {
            reactions: components["schemas"]["Reaction"][];
        };
        Reaction: {
            /** Format: date-time */
            created_at: string;
            emoji: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            message_id: string;
            /** Format: uuid */
            user_id: string;
        };
        SearchResponse: {
            conversations: components["schemas"]["ConversationMessage"][];
            data: components["schemas"]["Message"][];
        };
        /**
         * @description Channels and conversations are different resources with different visibility
         *     rules, so they are returned as two lists rather than merged into one. A
         *     caller that filters by channel is asking about channels and gets nothing else.
         * @enum {string}
         */
        SearchScope: "channels" | "conversations" | "all";
        SendMessageRequest: {
            /**
             * Format: uuid
             * @description The sender's own id for this send, used only to make a retry idempotent.
             *     It is not the message id — the server owns that.
             */
            client_message_id?: string | null;
            content: string;
            /** Format: uuid */
            thread_parent_id?: string | null;
        };
        StatusResponse: {
            status: string;
        };
        UpdateMessageRequest: {
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_messages: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                ch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataList_MessageWithReactions"];
                };
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    list_pins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataList_Message"];
                };
            };
        };
    };
    mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    delete_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    update_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMessageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    message_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataList_MessageEdit"];
                };
            };
        };
    };
    pin_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    unpin_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_reactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataList_Reaction"];
                };
            };
        };
    };
    add_reaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddReactionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reaction"];
                };
            };
        };
    };
    remove_reaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
                emoji: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_thread: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataList_Message"];
                };
            };
        };
    };
    reply_to_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                msg_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    search_messages: {
        parameters: {
            query: {
                q?: string | null;
                workspace_id: string;
                channel_id?: string | null;
                user_id?: string | null;
                limit?: number | null;
                offset?: number | null;
                scope?: null | components["schemas"]["SearchScope"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
}
