/// The shortcodes the composer already resolves to a Unicode emoji. A custom
/// `:smile:` would upload fine and then never render, because the renderer
/// resolves the standard set first -- so the upload is refused instead of
/// producing an emoji that silently does nothing.
///
/// Kept in step with `frontend/src/lib/emojiShortcodes.ts` by hand; it is a
/// static list that has not changed in the life of the project, and the
/// alternative is a build step for eighty-eight strings.
pub const STANDARD_SHORTCODES: &[&str] = &[
    "alien",
    "angry",
    "beer",
    "bell",
    "black_heart",
    "blue_heart",
    "blush",
    "boom",
    "broken_heart",
    "bulb",
    "cake",
    "check",
    "clap",
    "clown",
    "coffee",
    "cold_sweat",
    "confetti_ball",
    "cry",
    "dart",
    "exclamation",
    "exploding_head",
    "expressionless",
    "eyes",
    "fingers_crossed",
    "fire",
    "flushed",
    "ghost",
    "green_heart",
    "grin",
    "grinning",
    "handshake",
    "heart",
    "heart_eyes",
    "hearts",
    "joy",
    "kissing_heart",
    "laughing",
    "muscle",
    "nauseated_face",
    "neutral_face",
    "ok_hand",
    "orange_heart",
    "partying_face",
    "pizza",
    "pleading_face",
    "point_up",
    "poop",
    "pray",
    "purple_heart",
    "pushpin",
    "question",
    "rage",
    "raised_hands",
    "robot",
    "rocket",
    "rofl",
    "salute",
    "skull",
    "sleeping",
    "slightly_smiling_face",
    "smile",
    "smiley",
    "smirk",
    "sob",
    "sparkles",
    "speech_balloon",
    "star",
    "star2",
    "star_struck",
    "stuck_out_tongue",
    "sunglasses",
    "sweat_smile",
    "tada",
    "thinking",
    "thumbsdown",
    "thumbsup",
    "trophy",
    "unamused",
    "upside_down_face",
    "v",
    "warning",
    "wave",
    "white_check_mark",
    "wink",
    "x",
    "yellow_heart",
    "yum",
    "zap",
];

pub fn shadows_a_standard_emoji(name: &str) -> bool {
    STANDARD_SHORTCODES.contains(&name)
}
