import { Extension, InputRule } from '@tiptap/core';

export const EMOJI_SHORTCODES: Record<string, string> = {
  smile: '😄',
  smiley: '😃',
  grin: '😁',
  grinning: '😀',
  laughing: '😆',
  joy: '😂',
  rofl: '🤣',
  sweat_smile: '😅',
  wink: '😉',
  blush: '😊',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  heart_eyes: '😍',
  kissing_heart: '😘',
  yum: '😋',
  stuck_out_tongue: '😛',
  thinking: '🤔',
  neutral_face: '😐',
  expressionless: '😑',
  unamused: '😒',
  smirk: '😏',
  flushed: '😳',
  cold_sweat: '😰',
  sob: '😭',
  cry: '😢',
  angry: '😠',
  rage: '😡',
  sunglasses: '😎',
  sleeping: '😴',
  nauseated_face: '🤮',
  exploding_head: '🤯',
  partying_face: '🥳',
  star_struck: '🤩',
  pleading_face: '🥺',
  ghost: '👻',
  skull: '💀',
  poop: '💩',
  robot: '🤖',
  alien: '👽',
  clown: '🤡',
  eyes: '👀',
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  ok_hand: '👌',
  clap: '👏',
  raised_hands: '🙌',
  pray: '🙏',
  wave: '👋',
  muscle: '💪',
  point_up: '☝️',
  v: '✌️',
  fingers_crossed: '🤞',
  handshake: '🤝',
  salute: '🫡',
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  broken_heart: '💔',
  hearts: '💕',
  fire: '🔥',
  sparkles: '✨',
  star: '⭐',
  star2: '🌟',
  zap: '⚡',
  boom: '💥',
  '100': '💯',
  tada: '🎉',
  confetti_ball: '🎊',
  trophy: '🏆',
  rocket: '🚀',
  bell: '🔔',
  bulb: '💡',
  pushpin: '📌',
  dart: '🎯',
  speech_balloon: '💬',
  white_check_mark: '✅',
  check: '✅',
  x: '❌',
  warning: '⚠️',
  question: '❓',
  exclamation: '❗',
  coffee: '☕',
  beer: '🍺',
  pizza: '🍕',
  cake: '🎂',
};

export const EmojiShortcodes = Extension.create({
  name: 'emojiShortcodes',
  addInputRules() {
    return [
      new InputRule({
        find: /:([a-zA-Z0-9_+-]+):$/,
        handler: ({ state, range, match }) => {
          const emoji = EMOJI_SHORTCODES[match[1].toLowerCase()];
          if (emoji) {
            state.tr.insertText(emoji, range.from, range.to);
          }
        },
      }),
    ];
  },
});
